#!/bin/sh

SRC_ROOT=/home/gxh/works/huichang/svc_webrtc/bizconf_rtc_endpoint/webrtc-checkout/src/out/linux_openssl/obj/
DST_ROOT=`pwd`/../ffmpeg-linux/mylib/

ar rcs $DST_ROOT/libwebrtc.a \
$SRC_ROOT/api/video/video_frame_i420/i420_buffer.o \
$SRC_ROOT/api/video/video_frame_i420/i420_buffer.dwo \
$SRC_ROOT/api/video/video_frame/color_space.o \
$SRC_ROOT/api/video/video_frame/color_space.dwo \
$SRC_ROOT/api/video/video_frame/hdr_metadata.o \
$SRC_ROOT/api/video/video_frame/hdr_metadata.dwo \
$SRC_ROOT/api/video/video_frame/video_content_type.o \
$SRC_ROOT/api/video/video_frame/video_content_type.dwo \
$SRC_ROOT/api/video/video_frame/video_frame_buffer.o \
$SRC_ROOT/api/video/video_frame/video_frame_buffer.dwo \
$SRC_ROOT/api/video/video_frame/video_frame.o \
$SRC_ROOT/api/video/video_frame/video_frame.dwo \
$SRC_ROOT/api/video/video_frame/video_source_interface.o \
$SRC_ROOT/api/video/video_frame/video_source_interface.dwo \
$SRC_ROOT/api/video/video_frame/video_timing.o \
$SRC_ROOT/api/video/video_frame/video_timing.dwo \
$SRC_ROOT/common_video/common_video/i420_buffer_pool.o \
$SRC_ROOT/common_video/common_video/i420_buffer_pool.dwo \
$SRC_ROOT/modules/video_processing/video_processing/denoiser_filter_c.o \
$SRC_ROOT/modules/video_processing/video_processing/denoiser_filter_c.dwo \
$SRC_ROOT/modules/video_processing/video_processing/denoiser_filter.o \
$SRC_ROOT/modules/video_processing/video_processing/denoiser_filter.dwo \
$SRC_ROOT/modules/video_processing/video_processing/noise_estimation.o \
$SRC_ROOT/modules/video_processing/video_processing/noise_estimation.dwo \
$SRC_ROOT/modules/video_processing/video_processing/skin_detection.o \
$SRC_ROOT/modules/video_processing/video_processing/skin_detection.dwo \
$SRC_ROOT/modules/video_processing/video_processing/video_denoiser.o \
$SRC_ROOT/modules/video_processing/video_processing/video_denoiser.dwo \
$SRC_ROOT/modules/video_processing/video_processing_sse2/denoiser_filter_sse2.o \
$SRC_ROOT/modules/video_processing/video_processing_sse2/denoiser_filter_sse2.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/compare_common.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/compare_common.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/compare_gcc.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/compare_gcc.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/compare.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/compare.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_argb.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_argb.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_from_argb.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_from_argb.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_from.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_from.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_jpeg.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_jpeg.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_to_argb.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_to_argb.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_to_i420.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert_to_i420.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/convert.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/cpu_id.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/cpu_id.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/mjpeg_decoder.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/mjpeg_decoder.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/mjpeg_validate.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/mjpeg_validate.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/planar_functions.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/planar_functions.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate_any.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate_any.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate_argb.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate_argb.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate_common.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate_common.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate_gcc.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate_gcc.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/rotate.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/row_any.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/row_any.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/row_common.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/row_common.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/row_gcc.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/row_gcc.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale_any.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale_any.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale_argb.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale_argb.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale_common.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale_common.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale_gcc.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale_gcc.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/scale.dwo \
$SRC_ROOT/third_party/libyuv/libyuv_internal/video_common.o \
$SRC_ROOT/third_party/libyuv/libyuv_internal/video_common.dwo \
$SRC_ROOT/rtc_base/memory/aligned_malloc/aligned_malloc.o \
$SRC_ROOT/rtc_base/memory/aligned_malloc/aligned_malloc.dwo \
$SRC_ROOT/rtc_base/checks/checks.o \
$SRC_ROOT/rtc_base/checks/checks.dwo \
$SRC_ROOT/rtc_base/rtc_base_approved/race_checker.o \
$SRC_ROOT/rtc_base/rtc_base_approved/race_checker.dwo \
$SRC_ROOT/rtc_base/platform_thread_types/platform_thread_types.o \
$SRC_ROOT/rtc_base/platform_thread_types/platform_thread_types.dwo \
$SRC_ROOT/modules/audio_processing/aec/aec/aec_resampler.o \
$SRC_ROOT/modules/audio_processing/aec/aec/aec_resampler.dwo \
$SRC_ROOT/modules/audio_processing/aec/aec/echo_cancellation.o \
$SRC_ROOT/modules/audio_processing/aec/aec/echo_cancellation.dwo \
$SRC_ROOT/modules/audio_processing/aec/aec_core/aec_core_sse2.o \
$SRC_ROOT/modules/audio_processing/aec/aec_core/aec_core_sse2.dwo \
$SRC_ROOT/modules/audio_processing/aec/aec_core/aec_core.o \
$SRC_ROOT/modules/audio_processing/aec/aec_core/aec_core.dwo \
$SRC_ROOT/modules/audio_processing/aec_dump/null_aec_dump_factory/null_aec_dump_factory.o \
$SRC_ROOT/modules/audio_processing/aec_dump/null_aec_dump_factory/null_aec_dump_factory.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/adaptive_fir_filter.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/adaptive_fir_filter.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/aec_state.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/aec_state.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/aec3_common.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/aec3_common.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/aec3_fft.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/aec3_fft.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/api_call_jitter_metrics.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/api_call_jitter_metrics.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/block_delay_buffer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/block_delay_buffer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/block_framer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/block_framer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/block_processor_metrics.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/block_processor_metrics.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/block_processor.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/block_processor.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/cascaded_biquad_filter.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/cascaded_biquad_filter.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/clockdrift_detector.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/clockdrift_detector.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/comfort_noise_generator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/comfort_noise_generator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/decimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/decimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/downsampled_render_buffer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/downsampled_render_buffer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_audibility.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_audibility.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_canceller3.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_canceller3.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_path_delay_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_path_delay_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_path_variability.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_path_variability.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_remover_metrics.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_remover_metrics.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_remover.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/echo_remover.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/erl_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/erl_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/erle_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/erle_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/fft_buffer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/fft_buffer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/filter_analyzer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/filter_analyzer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/frame_blocker.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/frame_blocker.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/fullband_erle_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/fullband_erle_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/main_filter_update_gain.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/main_filter_update_gain.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/matched_filter_lag_aggregator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/matched_filter_lag_aggregator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/matched_filter.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/matched_filter.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/matrix_buffer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/matrix_buffer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/moving_average.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/moving_average.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_buffer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_buffer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_delay_buffer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_delay_buffer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_delay_controller_metrics.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_delay_controller_metrics.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_delay_controller.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_delay_controller.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_reverb_model.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_reverb_model.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_signal_analyzer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/render_signal_analyzer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/residual_echo_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/residual_echo_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_decay_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_decay_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_frequency_response.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_frequency_response.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_model_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_model_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_model_fallback.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_model_fallback.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_model.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/reverb_model.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/shadow_filter_update_gain.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/shadow_filter_update_gain.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/signal_dependent_erle_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/signal_dependent_erle_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/skew_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/skew_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/stationarity_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/stationarity_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/subband_erle_estimator.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/subband_erle_estimator.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/subtractor_output_analyzer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/subtractor_output_analyzer.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/subtractor_output.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/subtractor_output.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/subtractor.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/subtractor.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/suppression_filter.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/suppression_filter.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/suppression_gain.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/suppression_gain.dwo \
$SRC_ROOT/modules/audio_processing/aec3/aec3/vector_buffer.o \
$SRC_ROOT/modules/audio_processing/aec3/aec3/vector_buffer.dwo \
$SRC_ROOT/modules/audio_processing/aecm/aecm_core/aecm_core_c.o \
$SRC_ROOT/modules/audio_processing/aecm/aecm_core/aecm_core_c.dwo \
$SRC_ROOT/modules/audio_processing/aecm/aecm_core/aecm_core.o \
$SRC_ROOT/modules/audio_processing/aecm/aecm_core/aecm_core.dwo \
$SRC_ROOT/modules/audio_processing/aecm/aecm_core/echo_control_mobile.o \
$SRC_ROOT/modules/audio_processing/aecm/aecm_core/echo_control_mobile.dwo \
$SRC_ROOT/modules/audio_processing/agc/agc/agc_manager_direct.o \
$SRC_ROOT/modules/audio_processing/agc/agc/agc_manager_direct.dwo \
$SRC_ROOT/modules/audio_processing/agc/agc_legacy_c/analog_agc.o \
$SRC_ROOT/modules/audio_processing/agc/agc_legacy_c/analog_agc.dwo \
$SRC_ROOT/modules/audio_processing/agc/agc_legacy_c/digital_agc.o \
$SRC_ROOT/modules/audio_processing/agc/agc_legacy_c/digital_agc.dwo \
$SRC_ROOT/modules/audio_processing/agc/level_estimation/agc.o \
$SRC_ROOT/modules/audio_processing/agc/level_estimation/agc.dwo \
$SRC_ROOT/modules/audio_processing/agc/level_estimation/loudness_histogram.o \
$SRC_ROOT/modules/audio_processing/agc/level_estimation/loudness_histogram.dwo \
$SRC_ROOT/modules/audio_processing/agc/level_estimation/utility.o \
$SRC_ROOT/modules/audio_processing/agc/level_estimation/utility.dwo \
$SRC_ROOT/modules/audio_processing/agc2/adaptive_digital/adaptive_agc.o \
$SRC_ROOT/modules/audio_processing/agc2/adaptive_digital/adaptive_agc.dwo \
$SRC_ROOT/modules/audio_processing/agc2/adaptive_digital/adaptive_digital_gain_applier.o \
$SRC_ROOT/modules/audio_processing/agc2/adaptive_digital/adaptive_digital_gain_applier.dwo \
$SRC_ROOT/modules/audio_processing/agc2/adaptive_digital/adaptive_mode_level_estimator.o \
$SRC_ROOT/modules/audio_processing/agc2/adaptive_digital/adaptive_mode_level_estimator.dwo \
$SRC_ROOT/modules/audio_processing/agc2/adaptive_digital/saturation_protector.o \
$SRC_ROOT/modules/audio_processing/agc2/adaptive_digital/saturation_protector.dwo \
$SRC_ROOT/modules/audio_processing/agc2/biquad_filter/biquad_filter.o \
$SRC_ROOT/modules/audio_processing/agc2/biquad_filter/biquad_filter.dwo \
$SRC_ROOT/modules/audio_processing/agc2/common/agc2_common.o \
$SRC_ROOT/modules/audio_processing/agc2/common/agc2_common.dwo \
$SRC_ROOT/modules/audio_processing/agc2/fixed_digital/fixed_digital_level_estimator.o \
$SRC_ROOT/modules/audio_processing/agc2/fixed_digital/fixed_digital_level_estimator.dwo \
$SRC_ROOT/modules/audio_processing/agc2/fixed_digital/interpolated_gain_curve.o \
$SRC_ROOT/modules/audio_processing/agc2/fixed_digital/interpolated_gain_curve.dwo \
$SRC_ROOT/modules/audio_processing/agc2/fixed_digital/limiter.o \
$SRC_ROOT/modules/audio_processing/agc2/fixed_digital/limiter.dwo \
$SRC_ROOT/modules/audio_processing/agc2/gain_applier/gain_applier.o \
$SRC_ROOT/modules/audio_processing/agc2/gain_applier/gain_applier.dwo \
$SRC_ROOT/modules/audio_processing/agc2/level_estimation_agc/adaptive_mode_level_estimator_agc.o \
$SRC_ROOT/modules/audio_processing/agc2/level_estimation_agc/adaptive_mode_level_estimator_agc.dwo \
$SRC_ROOT/modules/audio_processing/agc2/noise_level_estimator/down_sampler.o \
$SRC_ROOT/modules/audio_processing/agc2/noise_level_estimator/down_sampler.dwo \
$SRC_ROOT/modules/audio_processing/agc2/noise_level_estimator/noise_level_estimator.o \
$SRC_ROOT/modules/audio_processing/agc2/noise_level_estimator/noise_level_estimator.dwo \
$SRC_ROOT/modules/audio_processing/agc2/noise_level_estimator/noise_spectrum_estimator.o \
$SRC_ROOT/modules/audio_processing/agc2/noise_level_estimator/noise_spectrum_estimator.dwo \
$SRC_ROOT/modules/audio_processing/agc2/noise_level_estimator/signal_classifier.o \
$SRC_ROOT/modules/audio_processing/agc2/noise_level_estimator/signal_classifier.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/features_extraction.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/features_extraction.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/fft_util.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/fft_util.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/lp_residual.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/lp_residual.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/pitch_search_internal.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/pitch_search_internal.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/pitch_search.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/pitch_search.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/rnn.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/rnn.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/spectral_features_internal.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/spectral_features_internal.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/spectral_features.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad/rnn_vad/spectral_features.dwo \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad_with_level/vad_with_level.o \
$SRC_ROOT/modules/audio_processing/agc2/rnn_vad_with_level/vad_with_level.dwo \
$SRC_ROOT/modules/audio_processing/api/audio_processing.o \
$SRC_ROOT/modules/audio_processing/api/audio_processing.dwo \
$SRC_ROOT/modules/audio_processing/apm_logging/apm_data_dumper.o \
$SRC_ROOT/modules/audio_processing/apm_logging/apm_data_dumper.dwo \
$SRC_ROOT/modules/audio_processing/audio_buffer/audio_buffer.o \
$SRC_ROOT/modules/audio_processing/audio_buffer/audio_buffer.dwo \
$SRC_ROOT/modules/audio_processing/audio_buffer/splitting_filter.o \
$SRC_ROOT/modules/audio_processing/audio_buffer/splitting_filter.dwo \
$SRC_ROOT/modules/audio_processing/audio_buffer/three_band_filter_bank.o \
$SRC_ROOT/modules/audio_processing/audio_buffer/three_band_filter_bank.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/aec_dump.o \
$SRC_ROOT/modules/audio_processing/audio_processing/aec_dump.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/audio_processing_impl.o \
$SRC_ROOT/modules/audio_processing/audio_processing/audio_processing_impl.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/circular_buffer.o \
$SRC_ROOT/modules/audio_processing/audio_processing/circular_buffer.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/echo_cancellation_impl.o \
$SRC_ROOT/modules/audio_processing/audio_processing/echo_cancellation_impl.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/echo_control_mobile_impl.o \
$SRC_ROOT/modules/audio_processing/audio_processing/echo_control_mobile_impl.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/gain_control_for_experimental_agc.o \
$SRC_ROOT/modules/audio_processing/audio_processing/gain_control_for_experimental_agc.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/gain_control_impl.o \
$SRC_ROOT/modules/audio_processing/audio_processing/gain_control_impl.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/gain_controller2.o \
$SRC_ROOT/modules/audio_processing/audio_processing/gain_controller2.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/level_estimator_impl.o \
$SRC_ROOT/modules/audio_processing/audio_processing/level_estimator_impl.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/low_cut_filter.o \
$SRC_ROOT/modules/audio_processing/audio_processing/low_cut_filter.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/mean_variance_estimator.o \
$SRC_ROOT/modules/audio_processing/audio_processing/mean_variance_estimator.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/moving_max.o \
$SRC_ROOT/modules/audio_processing/audio_processing/moving_max.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/moving_moments.o \
$SRC_ROOT/modules/audio_processing/audio_processing/moving_moments.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/noise_suppression_impl.o \
$SRC_ROOT/modules/audio_processing/audio_processing/noise_suppression_impl.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/normalized_covariance_estimator.o \
$SRC_ROOT/modules/audio_processing/audio_processing/normalized_covariance_estimator.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/residual_echo_detector.o \
$SRC_ROOT/modules/audio_processing/audio_processing/residual_echo_detector.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/rms_level.o \
$SRC_ROOT/modules/audio_processing/audio_processing/rms_level.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/transient_detector.o \
$SRC_ROOT/modules/audio_processing/audio_processing/transient_detector.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/transient_suppressor.o \
$SRC_ROOT/modules/audio_processing/audio_processing/transient_suppressor.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/typing_detection.o \
$SRC_ROOT/modules/audio_processing/audio_processing/typing_detection.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/voice_detection_impl.o \
$SRC_ROOT/modules/audio_processing/audio_processing/voice_detection_impl.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/wpd_node.o \
$SRC_ROOT/modules/audio_processing/audio_processing/wpd_node.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing/wpd_tree.o \
$SRC_ROOT/modules/audio_processing/audio_processing/wpd_tree.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing_c/noise_suppression.o \
$SRC_ROOT/modules/audio_processing/audio_processing_c/noise_suppression.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing_c/ns_core.o \
$SRC_ROOT/modules/audio_processing/audio_processing_c/ns_core.dwo \
$SRC_ROOT/modules/audio_processing/audio_processing_statistics/audio_processing_statistics.o \
$SRC_ROOT/modules/audio_processing/audio_processing_statistics/audio_processing_statistics.dwo \
$SRC_ROOT/modules/audio_processing/config/config.o \
$SRC_ROOT/modules/audio_processing/config/config.dwo \
$SRC_ROOT/modules/audio_processing/noise_suppression_proxy/noise_suppression_proxy.o \
$SRC_ROOT/modules/audio_processing/noise_suppression_proxy/noise_suppression_proxy.dwo \
$SRC_ROOT/modules/audio_processing/utility/block_mean_calculator/block_mean_calculator.o \
$SRC_ROOT/modules/audio_processing/utility/block_mean_calculator/block_mean_calculator.dwo \
$SRC_ROOT/modules/audio_processing/utility/legacy_delay_estimator/delay_estimator_wrapper.o \
$SRC_ROOT/modules/audio_processing/utility/legacy_delay_estimator/delay_estimator_wrapper.dwo \
$SRC_ROOT/modules/audio_processing/utility/legacy_delay_estimator/delay_estimator.o \
$SRC_ROOT/modules/audio_processing/utility/legacy_delay_estimator/delay_estimator.dwo \
$SRC_ROOT/modules/audio_processing/utility/ooura_fft/ooura_fft_sse2.o \
$SRC_ROOT/modules/audio_processing/utility/ooura_fft/ooura_fft_sse2.dwo \
$SRC_ROOT/modules/audio_processing/utility/ooura_fft/ooura_fft.o \
$SRC_ROOT/modules/audio_processing/utility/ooura_fft/ooura_fft.dwo \
$SRC_ROOT/modules/audio_processing/vad/vad/gmm.o \
$SRC_ROOT/modules/audio_processing/vad/vad/gmm.dwo \
$SRC_ROOT/modules/audio_processing/vad/vad/pitch_based_vad.o \
$SRC_ROOT/modules/audio_processing/vad/vad/pitch_based_vad.dwo \
$SRC_ROOT/modules/audio_processing/vad/vad/pitch_internal.o \
$SRC_ROOT/modules/audio_processing/vad/vad/pitch_internal.dwo \
$SRC_ROOT/modules/audio_processing/vad/vad/pole_zero_filter.o \
$SRC_ROOT/modules/audio_processing/vad/vad/pole_zero_filter.dwo \
$SRC_ROOT/modules/audio_processing/vad/vad/standalone_vad.o \
$SRC_ROOT/modules/audio_processing/vad/vad/standalone_vad.dwo \
$SRC_ROOT/modules/audio_processing/vad/vad/vad_audio_proc.o \
$SRC_ROOT/modules/audio_processing/vad/vad/vad_audio_proc.dwo \
$SRC_ROOT/modules/audio_processing/vad/vad/vad_circular_buffer.o \
$SRC_ROOT/modules/audio_processing/vad/vad/vad_circular_buffer.dwo \
$SRC_ROOT/modules/audio_processing/vad/vad/voice_activity_detector.o \
$SRC_ROOT/modules/audio_processing/vad/vad/voice_activity_detector.dwo \
$SRC_ROOT/audio/utility/audio_frame_operations/audio_frame_operations.o \
$SRC_ROOT/audio/utility/audio_frame_operations/audio_frame_operations.dwo \
$SRC_ROOT/rtc_base/rtc_base_approved/event_tracer.o \
$SRC_ROOT/rtc_base/rtc_base_approved/event_tracer.dwo \
$SRC_ROOT/rtc_base/criticalsection/critical_section.o \
$SRC_ROOT/rtc_base/criticalsection/critical_section.dwo \
$SRC_ROOT/rtc_base/logging/logging.o \
$SRC_ROOT/rtc_base/logging/logging.dwo \
$SRC_ROOT/rtc_base/timeutils/time_utils.o \
$SRC_ROOT/rtc_base/timeutils/time_utils.dwo \
$SRC_ROOT/rtc_base/platform_thread/platform_thread.o \
$SRC_ROOT/rtc_base/platform_thread/platform_thread.dwo \
$SRC_ROOT/rtc_base/rtc_event/event.o \
$SRC_ROOT/rtc_base/rtc_event/event.dwo \
$SRC_ROOT/rtc_base/thread_checker/thread_checker_impl.o \
$SRC_ROOT/rtc_base/thread_checker/thread_checker_impl.dwo \
$SRC_ROOT/rtc_base/stringutils/string_builder.o \
$SRC_ROOT/rtc_base/stringutils/string_builder.dwo \
$SRC_ROOT/rtc_base/stringutils/string_encode.o \
$SRC_ROOT/rtc_base/stringutils/string_encode.dwo \
$SRC_ROOT/rtc_base/stringutils/string_to_number.o \
$SRC_ROOT/rtc_base/stringutils/string_to_number.dwo \
$SRC_ROOT/rtc_base/stringutils/string_utils.o \
$SRC_ROOT/rtc_base/stringutils/string_utils.dwo \
$SRC_ROOT/api/audio/audio_frame_api/audio_frame.o \
$SRC_ROOT/api/audio/audio_frame_api/audio_frame.dwo \
$SRC_ROOT/api/audio/aec3_config/echo_canceller3_config.o \
$SRC_ROOT/api/audio/aec3_config/echo_canceller3_config.dwo \
$SRC_ROOT/system_wrappers/metrics/metrics.o \
$SRC_ROOT/system_wrappers/metrics/metrics.dwo \
$SRC_ROOT/system_wrappers/system_wrappers/cpu_features.o \
$SRC_ROOT/system_wrappers/system_wrappers/cpu_features.dwo \
$SRC_ROOT/system_wrappers/system_wrappers/cpu_info.o \
$SRC_ROOT/system_wrappers/system_wrappers/cpu_info.dwo \
$SRC_ROOT/system_wrappers/field_trial/field_trial.o \
$SRC_ROOT/system_wrappers/field_trial/field_trial.dwo \
$SRC_ROOT/common_audio/common_audio/audio_converter.o \
$SRC_ROOT/common_audio/common_audio/audio_converter.dwo \
$SRC_ROOT/common_audio/common_audio/audio_util.o \
$SRC_ROOT/common_audio/common_audio/audio_util.dwo \
$SRC_ROOT/common_audio/common_audio/channel_buffer.o \
$SRC_ROOT/common_audio/common_audio/channel_buffer.dwo \
$SRC_ROOT/common_audio/common_audio/push_resampler.o \
$SRC_ROOT/common_audio/common_audio/push_resampler.dwo \
$SRC_ROOT/common_audio/common_audio/push_sinc_resampler.o \
$SRC_ROOT/common_audio/common_audio/push_sinc_resampler.dwo \
$SRC_ROOT/common_audio/common_audio/real_fourier_ooura.o \
$SRC_ROOT/common_audio/common_audio/real_fourier_ooura.dwo \
$SRC_ROOT/common_audio/common_audio/real_fourier.o \
$SRC_ROOT/common_audio/common_audio/real_fourier.dwo \
$SRC_ROOT/common_audio/common_audio/resampler.o \
$SRC_ROOT/common_audio/common_audio/resampler.dwo \
$SRC_ROOT/common_audio/common_audio/sinc_resampler.o \
$SRC_ROOT/common_audio/common_audio/sinc_resampler.dwo \
$SRC_ROOT/common_audio/common_audio/smoothing_filter.o \
$SRC_ROOT/common_audio/common_audio/smoothing_filter.dwo \
$SRC_ROOT/common_audio/common_audio/sparse_fir_filter.o \
$SRC_ROOT/common_audio/common_audio/sparse_fir_filter.dwo \
$SRC_ROOT/common_audio/common_audio/vad.o \
$SRC_ROOT/common_audio/common_audio/vad.dwo \
$SRC_ROOT/common_audio/common_audio/wav_file.o \
$SRC_ROOT/common_audio/common_audio/wav_file.dwo \
$SRC_ROOT/common_audio/common_audio/wav_header.o \
$SRC_ROOT/common_audio/common_audio/wav_header.dwo \
$SRC_ROOT/common_audio/common_audio/window_generator.o \
$SRC_ROOT/common_audio/common_audio/window_generator.dwo \
$SRC_ROOT/common_audio/common_audio_c/auto_corr_to_refl_coef.o \
$SRC_ROOT/common_audio/common_audio_c/auto_corr_to_refl_coef.dwo \
$SRC_ROOT/common_audio/common_audio_c/auto_correlation.o \
$SRC_ROOT/common_audio/common_audio_c/auto_correlation.dwo \
$SRC_ROOT/common_audio/common_audio_c/complex_bit_reverse.o \
$SRC_ROOT/common_audio/common_audio_c/complex_bit_reverse.dwo \
$SRC_ROOT/common_audio/common_audio_c/complex_fft.o \
$SRC_ROOT/common_audio/common_audio_c/complex_fft.dwo \
$SRC_ROOT/common_audio/common_audio_c/copy_set_operations.o \
$SRC_ROOT/common_audio/common_audio_c/copy_set_operations.dwo \
$SRC_ROOT/common_audio/common_audio_c/cross_correlation.o \
$SRC_ROOT/common_audio/common_audio_c/cross_correlation.dwo \
$SRC_ROOT/common_audio/common_audio_c/division_operations.o \
$SRC_ROOT/common_audio/common_audio_c/division_operations.dwo \
$SRC_ROOT/common_audio/common_audio_c/downsample_fast.o \
$SRC_ROOT/common_audio/common_audio_c/downsample_fast.dwo \
$SRC_ROOT/common_audio/common_audio_c/energy.o \
$SRC_ROOT/common_audio/common_audio_c/energy.dwo \
$SRC_ROOT/common_audio/common_audio_c/filter_ar_fast_q12.o \
$SRC_ROOT/common_audio/common_audio_c/filter_ar_fast_q12.dwo \
$SRC_ROOT/common_audio/common_audio_c/filter_ar.o \
$SRC_ROOT/common_audio/common_audio_c/filter_ar.dwo \
$SRC_ROOT/common_audio/common_audio_c/filter_ma_fast_q12.o \
$SRC_ROOT/common_audio/common_audio_c/filter_ma_fast_q12.dwo \
$SRC_ROOT/common_audio/common_audio_c/get_hanning_window.o \
$SRC_ROOT/common_audio/common_audio_c/get_hanning_window.dwo \
$SRC_ROOT/common_audio/common_audio_c/get_scaling_square.o \
$SRC_ROOT/common_audio/common_audio_c/get_scaling_square.dwo \
$SRC_ROOT/common_audio/common_audio_c/ilbc_specific_functions.o \
$SRC_ROOT/common_audio/common_audio_c/ilbc_specific_functions.dwo \
$SRC_ROOT/common_audio/common_audio_c/levinson_durbin.o \
$SRC_ROOT/common_audio/common_audio_c/levinson_durbin.dwo \
$SRC_ROOT/common_audio/common_audio_c/lpc_to_refl_coef.o \
$SRC_ROOT/common_audio/common_audio_c/lpc_to_refl_coef.dwo \
$SRC_ROOT/common_audio/common_audio_c/min_max_operations.o \
$SRC_ROOT/common_audio/common_audio_c/min_max_operations.dwo \
$SRC_ROOT/common_audio/common_audio_c/randomization_functions.o \
$SRC_ROOT/common_audio/common_audio_c/randomization_functions.dwo \
$SRC_ROOT/common_audio/common_audio_c/real_fft.o \
$SRC_ROOT/common_audio/common_audio_c/real_fft.dwo \
$SRC_ROOT/common_audio/common_audio_c/refl_coef_to_lpc.o \
$SRC_ROOT/common_audio/common_audio_c/refl_coef_to_lpc.dwo \
$SRC_ROOT/common_audio/common_audio_c/resample_48khz.o \
$SRC_ROOT/common_audio/common_audio_c/resample_48khz.dwo \
$SRC_ROOT/common_audio/common_audio_c/resample_by_2_internal.o \
$SRC_ROOT/common_audio/common_audio_c/resample_by_2_internal.dwo \
$SRC_ROOT/common_audio/common_audio_c/resample_by_2.o \
$SRC_ROOT/common_audio/common_audio_c/resample_by_2.dwo \
$SRC_ROOT/common_audio/common_audio_c/resample_fractional.o \
$SRC_ROOT/common_audio/common_audio_c/resample_fractional.dwo \
$SRC_ROOT/common_audio/common_audio_c/resample.o \
$SRC_ROOT/common_audio/common_audio_c/resample.dwo \
$SRC_ROOT/common_audio/common_audio_c/ring_buffer.o \
$SRC_ROOT/common_audio/common_audio_c/ring_buffer.dwo \
$SRC_ROOT/common_audio/common_audio_c/spl_init.o \
$SRC_ROOT/common_audio/common_audio_c/spl_init.dwo \
$SRC_ROOT/common_audio/common_audio_c/spl_inl.o \
$SRC_ROOT/common_audio/common_audio_c/spl_inl.dwo \
$SRC_ROOT/common_audio/common_audio_c/spl_sqrt.o \
$SRC_ROOT/common_audio/common_audio_c/spl_sqrt.dwo \
$SRC_ROOT/common_audio/common_audio_c/splitting_filter.o \
$SRC_ROOT/common_audio/common_audio_c/splitting_filter.dwo \
$SRC_ROOT/common_audio/common_audio_c/sqrt_of_one_minus_x_squared.o \
$SRC_ROOT/common_audio/common_audio_c/sqrt_of_one_minus_x_squared.dwo \
$SRC_ROOT/common_audio/common_audio_c/vad_core.o \
$SRC_ROOT/common_audio/common_audio_c/vad_core.dwo \
$SRC_ROOT/common_audio/common_audio_c/vad_filterbank.o \
$SRC_ROOT/common_audio/common_audio_c/vad_filterbank.dwo \
$SRC_ROOT/common_audio/common_audio_c/vad_gmm.o \
$SRC_ROOT/common_audio/common_audio_c/vad_gmm.dwo \
$SRC_ROOT/common_audio/common_audio_c/vad_sp.o \
$SRC_ROOT/common_audio/common_audio_c/vad_sp.dwo \
$SRC_ROOT/common_audio/common_audio_c/vector_scaling_operations.o \
$SRC_ROOT/common_audio/common_audio_c/vector_scaling_operations.dwo \
$SRC_ROOT/common_audio/common_audio_c/webrtc_vad.o \
$SRC_ROOT/common_audio/common_audio_c/webrtc_vad.dwo \
$SRC_ROOT/common_audio/common_audio_cc/dot_product_with_scale.o \
$SRC_ROOT/common_audio/common_audio_cc/dot_product_with_scale.dwo \
$SRC_ROOT/common_audio/common_audio_sse2/fir_filter_sse.o \
$SRC_ROOT/common_audio/common_audio_sse2/fir_filter_sse.dwo \
$SRC_ROOT/common_audio/common_audio_sse2/sinc_resampler_sse.o \
$SRC_ROOT/common_audio/common_audio_sse2/sinc_resampler_sse.dwo \
$SRC_ROOT/common_audio/fir_filter_factory/fir_filter_c.o \
$SRC_ROOT/common_audio/fir_filter_factory/fir_filter_c.dwo \
$SRC_ROOT/common_audio/fir_filter_factory/fir_filter_factory.o \
$SRC_ROOT/common_audio/fir_filter_factory/fir_filter_factory.dwo \
$SRC_ROOT/common_audio/third_party/fft4g/fft4g/fft4g.o \
$SRC_ROOT/common_audio/third_party/fft4g/fft4g/fft4g.dwo \
$SRC_ROOT/common_audio/third_party/spl_sqrt_floor/spl_sqrt_floor/spl_sqrt_floor.o \
$SRC_ROOT/common_audio/third_party/spl_sqrt_floor/spl_sqrt_floor/spl_sqrt_floor.dwo \
$SRC_ROOT/third_party/rnnoise/kiss_fft/kiss_fft.o \
$SRC_ROOT/third_party/rnnoise/kiss_fft/kiss_fft.dwo \
$SRC_ROOT/third_party/rnnoise/rnn_vad/rnn_vad_weights.o \
$SRC_ROOT/third_party/rnnoise/rnn_vad/rnn_vad_weights.dwo \
$SRC_ROOT/third_party/abseil-cpp/absl/types/bad_optional_access/bad_optional_access.o \
$SRC_ROOT/third_party/abseil-cpp/absl/types/bad_optional_access/bad_optional_access.dwo \
$SRC_ROOT/third_party/abseil-cpp/absl/base/base/raw_logging.o \
$SRC_ROOT/third_party/abseil-cpp/absl/base/base/raw_logging.dwo \
$SRC_ROOT/modules/audio_coding/isac/audio_decoder_isac.o \
$SRC_ROOT/modules/audio_coding/isac/audio_decoder_isac.dwo \
$SRC_ROOT/modules/audio_coding/isac/audio_encoder_isac.o \
$SRC_ROOT/modules/audio_coding/isac/audio_encoder_isac.dwo \
$SRC_ROOT/modules/audio_coding/isac_common/locked_bandwidth_info.o \
$SRC_ROOT/modules/audio_coding/isac_common/locked_bandwidth_info.dwo \
$SRC_ROOT/modules/audio_coding/isac_vad/filter_functions.o \
$SRC_ROOT/modules/audio_coding/isac_vad/filter_functions.dwo \
$SRC_ROOT/modules/audio_coding/isac_vad/isac_vad.o \
$SRC_ROOT/modules/audio_coding/isac_vad/isac_vad.dwo \
$SRC_ROOT/modules/audio_coding/isac_vad/pitch_estimator.o \
$SRC_ROOT/modules/audio_coding/isac_vad/pitch_estimator.dwo \
$SRC_ROOT/modules/audio_coding/isac_vad/pitch_filter.o \
$SRC_ROOT/modules/audio_coding/isac_vad/pitch_filter.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/arith_routines_hist.o \
$SRC_ROOT/modules/audio_coding/isac_c/arith_routines_hist.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/arith_routines_logist.o \
$SRC_ROOT/modules/audio_coding/isac_c/arith_routines_logist.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/arith_routines.o \
$SRC_ROOT/modules/audio_coding/isac_c/arith_routines.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/bandwidth_estimator.o \
$SRC_ROOT/modules/audio_coding/isac_c/bandwidth_estimator.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/crc.o \
$SRC_ROOT/modules/audio_coding/isac_c/crc.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/decode_bwe.o \
$SRC_ROOT/modules/audio_coding/isac_c/decode_bwe.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/decode.o \
$SRC_ROOT/modules/audio_coding/isac_c/decode.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/encode_lpc_swb.o \
$SRC_ROOT/modules/audio_coding/isac_c/encode_lpc_swb.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/encode.o \
$SRC_ROOT/modules/audio_coding/isac_c/encode.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/entropy_coding.o \
$SRC_ROOT/modules/audio_coding/isac_c/entropy_coding.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/filterbanks.o \
$SRC_ROOT/modules/audio_coding/isac_c/filterbanks.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/intialize.o \
$SRC_ROOT/modules/audio_coding/isac_c/intialize.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/isac.o \
$SRC_ROOT/modules/audio_coding/isac_c/isac.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/lattice.o \
$SRC_ROOT/modules/audio_coding/isac_c/lattice.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_analysis.o \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_analysis.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_gain_swb_tables.o \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_gain_swb_tables.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_shape_swb12_tables.o \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_shape_swb12_tables.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_shape_swb16_tables.o \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_shape_swb16_tables.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_tables.o \
$SRC_ROOT/modules/audio_coding/isac_c/lpc_tables.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/pitch_gain_tables.o \
$SRC_ROOT/modules/audio_coding/isac_c/pitch_gain_tables.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/pitch_lag_tables.o \
$SRC_ROOT/modules/audio_coding/isac_c/pitch_lag_tables.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/spectrum_ar_model_tables.o \
$SRC_ROOT/modules/audio_coding/isac_c/spectrum_ar_model_tables.dwo \
$SRC_ROOT/modules/audio_coding/isac_c/transform.o \
$SRC_ROOT/modules/audio_coding/isac_c/transform.dwo \










